networks:
  global-network:
  order-network:
    driver: bridge
  inventory-network:
    driver: bridge
  payment-network:
    driver: bridge
  product-network:
    driver: bridge
  gateway-redis-network:
    driver: bridge
  zipkin-network:
    driver: bridge
  auth:
    driver: bridge

services:
  discovery-server:
    container_name: discovery
    build:
     context: ./discovery
     dockerfile: ../Dockerfile
    profiles:
      - default
      - order
      - inventory
      - payment
      - product
      - gateway
    ports:
      - "8761:8761"

  order-postgres:
    image: postgres:15-alpine
    container_name: order_postgres_db
    networks:
      - order-network
    profiles:
      - default
      - order
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd1
      POSTGRES_DB: orderdb
#    ports:
#      - "5432:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data

  order-service:
    build:
      context: ./order
      dockerfile: ../Dockerfile
    depends_on:
      - order-postgres
      - discovery-server
    profiles:
      - default
      - order
    networks:
      - order-network
      - default
    deploy:
      replicas: 3
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-postgres:5432/orderdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pwd1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    ports:
#      - "8080:8080"

  inventory-postgres:
    image: postgres:15-alpine
    container_name: inventory_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd2
      POSTGRES_DB: inventorydb
    profiles:
      - default
      - inventory
    networks:
      - inventory-network
    volumes:
      - inventory_pgdata:/var/lib/postgresql/data

  inventory-service:
    build:
      context: ./inventory
      dockerfile: ../Dockerfile
    depends_on:
      - inventory-postgres
      - discovery-server
    profiles:
      - default
      - inventory
    deploy:
      replicas: 3
    networks:
      - inventory-network
      - default
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory_postgres_db:5432/inventorydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pwd2
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    ports:
#      - "8180:8080"

  payment-postgres:
    image: postgres:15-alpine
    container_name: payment_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd3
      POSTGRES_DB: paymentdb
    networks:
      - payment-network
    profiles:
      - default
      - payment
    volumes:
      - payment_pgdata:/var/lib/postgresql/data

  payment-service:
    build:
      context: ./payments
      dockerfile: ../Dockerfile
    depends_on:
      - inventory-postgres
      - discovery-server
    profiles:
      - default
      - payment
    deploy:
      replicas: 3
    networks:
      - payment-network
      - default
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-postgres:5432/paymentdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pwd3
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    ports:
#      - "8380:8080"

  mongo_db:
    image: mongo:6.0
    platform: linux/amd64
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27017:27017"
    networks:
      - product-network
    profiles:
      - default
      - product
    volumes:
      - mongo_data:/data/db

  product-service:
    build:
      context: ./product
      dockerfile: ../Dockerfile
    depends_on:
      - mongo_db
      - discovery-server
    profiles:
      - default
      - product
    deploy:
      replicas: 3
    networks:
      - product-network
      - default
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongo_db:27017/porductdb
#    ports:
#      - "8280:8080"

  gateway:
    build:
      context: ./gateway
      dockerfile: ../Dockerfile
    container_name: gateway
    ports:
      - "8080:8480"
#    depends_on:
#      - discovery-server
#      - payment-service
#      - product-service
#      - order-service
#      - inventory-service
#      - zipkin
    profiles:
      - default
      - gateway
    networks:
      - default
      - gateway-redis-network
      - order-network
      - payment-network
      - inventory-network
      - product-network
      - zipkin-network
    environment:
      - SPRING_PROFILES_ACTIVE=default

  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - gateway-redis-network
    profiles:
      - default
      - gateway
    volumes:
      - redis_data:/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
    networks:
      - default
    profiles:
      - default
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - prometheus
    profiles:
      - default
    restart: unless-stopped
  
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - default
    profiles:
      - default
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
#    ports:
#      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default
    profiles:
      - default
    volumes:
      - loki_data:/loki
    restart: unless-stopped

  keycloak_postgres:
    image: postgres:15
    container_name: keycloak_postgres
    restart: unless-stopped
    networks:
      - auth
    profiles:
      - default
      - auth
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak_postgres
      - KC_DB_PORT=5432
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8081:8080"
    networks:
      - global-network
      - auth
    profiles:
      - default
      - auth
    volumes:
      - ./data/keycloak:/opt/keycloak/data
    depends_on:
      - keycloak_postgres
    restart: unless-stopped

volumes:
  order_pgdata:
  inventory_pgdata:
  payment_pgdata:
  mongo_data:
  redis_data:
  loki_data:
  keycloak_pgdata:

