spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Habilita la detección automática de servicios en Eureka
          lower-case-service-id: true  # Usa nombres en minúsculas para los servicios

      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    export:
      prometheus:
        enabled: true